# Generated by Django 3.2.15 on 2023-09-10 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewInfo',
            fields=[
                ('interview', models.AutoField(primary_key=True, serialize=False)),
                ('total_question', models.IntegerField(default=1)),
                ('year_of_experience', models.IntegerField(default=0)),
                ('role', models.CharField(choices=[('IC', 'IC'), ('Manager', 'Manager')], max_length=20)),
                ('total_time', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('question_type', models.CharField(choices=[('HR', 'HR'), ('OT', 'other')], default='HR', max_length=20)),
                ('question_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='InterviewQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interview.interviewinfo')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interview.question')),
            ],
        ),
        migrations.AddField(
            model_name='interviewinfo',
            name='used_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interview.user'),
        ),
    ]
