# Generated by Django 3.2.15 on 2023-09-10 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interviewinfo',
            old_name='interview',
            new_name='interview_id',
        ),
        migrations.RenameField(
            model_name='interviewquestion',
            old_name='interview',
            new_name='interview_id',
        ),
        migrations.RenameField(
            model_name='interviewquestion',
            old_name='question',
            new_name='question_id',
        ),
    ]
