# Generated by Django 3.2.15 on 2023-09-11 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0002_auto_20230910_0552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('IC', 'IC'), ('Manager', 'Manager')], default='IC', max_length=20),
        ),
    ]
