# Generated by Django 3.2.15 on 2023-09-11 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0003_alter_question_question_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewquestion',
            name='question_index',
            field=models.IntegerField(default=0),
        ),
    ]
