# Generated by Django 3.2.15 on 2023-09-11 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0004_interviewquestion_question_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewquestion',
            name='question_index',
            field=models.IntegerField(default=1),
        ),
    ]
