# Generated by Django 3.2.15 on 2024-03-09 01:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewInfo',
            fields=[
                ('interview_id', models.AutoField(primary_key=True, serialize=False)),
                ('total_question', models.IntegerField(default=1)),
                ('year_of_experience', models.IntegerField(default=0)),
                ('role', models.CharField(choices=[('IC', 'IC'), ('Manager', 'Manager')], max_length=20)),
                ('total_time', models.IntegerField(default=0)),
                ('user_id', models.ForeignKey(default='test', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('question_role', models.CharField(choices=[('IC', 'IC'), ('Manager', 'Manager')], default='IC', max_length=20)),
                ('question_text', models.CharField(max_length=200)),
                ('question_type', models.CharField(choices=[('top10', 'top10'), ('communication', 'communication'), ('decision_making', 'decision_making'), ('teamwork', 'teamwork'), ('leadership', 'leadership')], default='communication', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='InterviewQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_index', models.IntegerField(default=1)),
                ('user_answer', models.CharField(max_length=2000)),
                ('access_answer', models.CharField(max_length=2000)),
                ('revise_answer', models.CharField(max_length=2000)),
                ('interview_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interview.interviewinfo')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interview.question')),
            ],
        ),
    ]
